name: Create repositories using IssueOps
description: This IssueOps takes the input from an user to create a repository based on Template Repository and safe settings
title: "[IssueOps]: "
labels: ["issueops", "triage"]
assignees:
  - kittychiu
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
  - type: input
    id: new-repository
    attributes:
      label: New Repository Name
      description: Type in the name of your new repository that applies the following permission
      placeholder: ex. new-repository
    validations:
      required: true
  - type: dropdown
    id: template-repository
    attributes:
      label: Template Repository
      description: Select Template Repository that you want to use
      options: # list of exisiting repo templates available in the organisation
        - repo-template1
    validations:
      required: true
  - type: input
    id: team
    attributes:
      label: Team Permission
      description: Type in the teams that you want to apply the admin permission. Separate team names by comma
      placeholder: ex. Team-1, Team-2
      options: # list of exisiting teams in the organisation
        - team-ai-developers
        - team-ux-developers
        - team-iot-developers
    validations:
      required: true
      
  - type: checkboxes
    id: enable-issues
    attributes:
      label: Enable Issues
      description: Do you want to enable issues?
      options:
        - label: Yes, I want to enable Issues
          required: false
          
  - type: checkboxes
    id: enable-project
    attributes:
      label: Enable Project
      description: Do you want to enable Projects?
      options:
        - label: Yes, I want to enable Projects
          required: false
          
  - type: checkboxes
    id: enable-squash-merge
    attributes:
      label: Allow Squash Merge
      description: Do you want to allow squash merge?
      options:
        - label: Yes, I want to allow squash merge
          required: false
     
  - type: checkboxes
    id: enable-forking
    attributes:
      label: Allow forking
      description: Do you want to enable forking?
      options:
        - label: Yes, I want to allow forking
          required: false
          
