name: Create repository with IssueOps
on:
  issues:
    types: [opened]   
  

jobs:
  Create-Repo:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'issueops')
    steps:
      # PAT requires at least admin:org, repo       
      - name: Create GitHub repo
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ISSUE_OPS_6 }}
          script: |            
            bodySplit = context.payload.issue.body.split("\r\n")
            console.log(bodySplit)
            console.log("New repository name: " + bodySplit[1])
            console.log("Template Repository: " + bodySplit[4])
            console.log("Team: " + bodySplit[7])
            console.log("Enable Issue: " +  bodySplit[10])
            console.log("Allow Squash Merge: " +  bodySplit[13])

            let newRepo = bodySplit[1]
            let templateRepo = bodySplit[4]
            let teams = bodySplit[7].split(",")
            let enableIssue = bodySplit[10]
            let enableSquashMerge = bodySplit[13]
            
            console.log("Calling GitHub API to create new repo: " + newRepo + " Template Repo: " + templateRepo + " Teams: " + teams)
            
            try {
              await github.rest.repos.createUsingTemplate({
                template_owner: context.payload.organization.login,
                template_repo: templateRepo,
                name: newRepo,
                owner: context.payload.organization.login,
                description: "This repo generated by IssueOps",
                include_all_branches: false,
                private: false
              })
            } catch(err) {
                throw err 
            }
            console.log("Repo created: " + newRepo)


            try {
              await github.rest.repos.update({
                owner: context.payload.organization.login,
                private: true,
                repo: newRepo,
                has_issues: enableIssue,
                has_projects: enableIssue,
                allow_squash_merge: enableSquashMerge
              })
            } catch(err) {
                throw err 
            }
            console.log("Enabled Issue: " + enableIssue)
            console.log("Enabled Project: " + enableIssue)
            
            try {
              await github.rest.repos.updateBranchProtection({
                "owner": context.payload.organization.login,
                "repo": newRepo,
                "branch": 'main',
                "required_status_checks": { "strict": true, "contexts": [] },
                "enforce_admins": true,
                "required_pull_request_reviews": {"dismissal_restrictions": {"users":[], "teams":[]}, "dismiss_stale_reviews": false, "require_code_owner_reviews": true, "required_approving_review_count": 1},
                "restrictions" : { "users": [], "teams": [], "apps": [] }
              })
            } catch(err) {
                throw err 
                
            }
            console.log("Enabled branch protection rules")
            
            try {
              await github.rest.teams.addOrUpdateRepoPermissionsInOrg({
                org: context.payload.organization.login,
                owner: context.payload.organization.login,
                repo: newRepo,
                team_slug: teams,
                permission: 'push'
              })
            } catch(err) {
                throw err 
            }
            console.log("Assigned team write permission: " + teams)

            
            try { 
              await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thanks for creating a repo. Your new repo is available at: https://github.com/' + context.payload.organization.login + "/" + newRepo
             }) 
            } catch(err) {
                throw err
            }
            console.log("Completed repo configurations")
