# This is a basic workflow to help you get started with Actions

name: Test secret

# Controls when the workflow will run
on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ${{ secrets.ISSUE_OPS_TEST }}
          echo ${{ secrets.SUPER_SECRET }}
          echo Hello, world!

      - name: Print Context
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.ISSUE_OPS_TEST }}
          script: |
            console.log("print context step")
            console.log( github-token )
